### ISSUE TITLE
Not abble to save

### ISSUE THREAD

**Issue by Avengers199999** [maikelwever/slimseditor#3]
By pure chance I found your git as I was looking for a save for R&C because I have a save "bug" where I can't get points in Hoverboard races and therefore can't get the robot costume.

The problem I have is that I decrypt the save with bruteforce, I can edit the USR-DATA file but when exporting or saving it, the values ​​of any option are not saved.

The save is from HD PS3 Edition.

**Comment by maikelwever** [comment]
The export button should 'just work', but I can confirm that the save button on PS3 was/is broken.

This should be fixed in version 0.0.5, which I just released. Please see [Releases](https://github.com/maikelwever/slimseditor/releases/tag/0.0.5) for binaries.

**Comment by Avengers199999** [comment]
Wow, so quick!!


Well, since I had the PS3 turned on and the tools on PC, I just tested the 0.0.5 and I can confirm that now it saves well. I have also put the save on the PS3 and it loads correctly.

maikelwever, thanks for the tool and the quick solution

**Comment by maikelwever** [comment]
You're welcome, I happened to be working on this project today anyway.

If you discovered or added new items to the editor, please consider contributing them back to this project.
